### ISSUE TITLE
Crash on iPad 7th generation

### ISSUE THREAD

**Issue by tothvoj-gl** [Tealium/tealium-react-native#34] opened 2019-10-28 11:29 UTC
Recently we have seen an increased number of crashes related to Tealium SDK. The crash is device specific and happens on the 7th generation iPad.

**Device**: iPad 7th generation 10,2 inches
**OS**: iOS 13

**Crash log:**
> Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1c24da98c __exceptionPreprocess
1  libobjc.A.dylib                0x1c22030a4 objc_exception_throw
2  CoreFoundation                 0x1c25303f8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1c253975c -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5
4  CoreFoundation                 0x1c23c75dc -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x1c23b9470 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  TealiumIOS                     0x10358646c +[TEALDeviceDataSources model:] + 188 (TEALDeviceDataSources.m:188)
7  TealiumIOS                     0x103585b10 -[TEALDeviceDataSources backgroundDataSources] + 63 (TEALDeviceDataSources.m:63)
8  TealiumIOS                     0x1035676f4 -[TEALDataSources backgroundSafeDataSources:] + 94 (TEALDataSources.m:94)
9  TealiumIOS                     0x10356ee00 __50-[Tealium trackType:title:dataSources:completion:]_block_invoke + 185 (Tealium.m:185)
10 libdispatch.dylib              0x1c21a7610 _dispatch_call_block_and_release
11 libdispatch.dylib              0x1c21a8184 _dispatch_client_callout
12 libdispatch.dylib              0x1c2154464 _dispatch_lane_serial_drain$VARIANT$mp
13 libdispatch.dylib              0x1c2154e58 _dispatch_lane_invoke$VARIANT$mp
14 libdispatch.dylib              0x1c215e340 _dispatch_workloop_worker_thread
15 libsystem_pthread.dylib        0x1c21f7fa4 _pthread_wqthread
16 libsystem_pthread.dylib        0x1c21faae0 start_wqthread

**Comment by christinasund** [comment] 2019-10-29 16:53
@tothvoj-gl Thank you for bringing this to us. We have identified the root cause and should have a new release out shortly. Thanks!

**Comment by jameskeith** [comment] 2019-11-01 10:51
@tothvoj-gl - thanks for your patience with this. This should be resolved in the latest release of our [iOS Objective C](https://github.com/Tealium/tealium-ios) library - version 5.6.3.
We've just released a new version of this react-native package that depends on v5.6.3 - so you should be able to update to resolve this issue.
please let us know if you have any further problems.

**Comment by tothvoj-gl** [comment] 2019-11-05 09:36
@jameskeith Thanks for the notice. We will try the new version and let you know. How can we ensure that this crash won't occur in the future? How will the SDK behave when there is a new iOS device?

**Comment by jameskeith** [comment] 2019-11-05 09:47
thanks @tothvoj-gl 
I believe the source of this crash was attributed to a recent release of the TealiumIOS SDK, and as such the latest tealium-react-native package depends on a later version that includes the fix.
We do update the device lists when there are new models etc, so expect to see our react native plugin updated to import those updated lists in future too.

**Comment by jameskeith** [comment] 2019-12-24 10:19
@tothvoj-gl - hopefully 1.0.7 resolved your issues. I'll close this issue off for now as we've not heard anything since November.
Please let us know if you still have this issue.

**Closed by jameskeith** 2019-12-24 10:19 UTC
