### ISSUE TITLE
null is not an object (evaluating 'tealium.module.intialize')

### ISSUE THREAD

**Issue by saurabh297** [Tealium/tealium-react-native#30] opened 2019-10-14 10:26 UTC
Hi I am trying using Tealium with react-native version-0.61.1 but its throwing this error.

**Comment by tamayok** [comment] 2019-10-14 16:09
@saurabh297 Thank you. We're currently looking into this.

**Comment by lutakyn** [comment] 2019-10-23 16:28
HI,im also having the same error

**Comment by jameskeith** [comment] 2019-11-01 11:18
Hopefully this should be resolved in the new release (1.0.7) so can we retest this with the latest package? as I'm not able to reproduce this on RN 0.61.2 and tealium-react-native 1.0.7

**Closed** 2019-12-24 10:21 UTC
