### ISSUE TITLE
Android startTealium doesn't kill previous tealium instance

### ISSUE THREAD

**Issue by ElAgroudyA** [Tealium/tealium-react-native#176] opened 2024-07-24 12:02 UTC
I made an [issue](https://github.com/Tealium/tealium-react-native/issues/174) before and it got closed as fixed while it doesn't.

The issue is on Android, starting tealium multiple times doesn't kill previous instances (as on iOS).

**Comment by jameskeith** [comment] 2024-07-24 13:04
@ElAgroudyA - Thanks for flagging this. 
I've just had a look through the previous issue, and that was explicitly related to `terminateInstance` not closing down the WebView - I'm unable to reproduce that issue anymore with the latest `tealium-react-native` package version `2.4.1` - tested by alternating between calling `initialize` and calling `terminateInstance`

Your description in this new issue seems to suggest that you are now calling `initialize` multiple times, without properly shutting down the previous instance first - i.e. through calling `Tealium.terminateInstance()` - and that this leads to more than one WebView instance.
Is that correct?

**Comment by ElAgroudyA** [comment] 2024-07-24 13:06
@jameskeith yeah true

**Comment by jameskeith** [comment] 2024-07-24 14:47
@ElAgroudyA - I'm happy to look at adding a check before initializing an instance, and shut down a previously running instance. I believe the intended behavior was for the user to shutdown their instances when they need to - hence the `terminateInstance` method available - as opposed to simply calling `initialize` several times.

Is this actually something you are seeing in your app under normal usage? or perhaps are you seeing this during development when RN auto-refreshes a view?

**Comment by ElAgroudyA** [comment] 2024-07-24 15:24
@jameskeith I understand your point and it would happen if you tested it by adding a button to initialize Tealium
I expect the SDK to work the same on both OSs but this is not the case since its handled in iOS but not Android, this will make me have the 'check' workaround in my code just for the Android to act as the iOS which I don't prefer to do.

**Comment by jameskeith** [comment] 2024-07-24 16:30
@ElAgroudyA - I think it's a reasonable assumption that the previous one would be shutdown (if already initialized) since we only support interacting with a single Tealium instance anyway. 
So I've raised a card internally to get the two platforms aligned, and we'll let you know once it's ready.

**Comment by ElAgroudyA** [comment] 2024-08-15 09:07
Hello @jameskeith 
any updates ?

**Comment by jameskeith** [comment] 2024-08-21 13:47
@ElAgroudyA - thanks for the nudge. It's on the way, should be available to release shortly.

**Comment by tamayok** [comment] 2024-08-21 18:55
@ElAgroudyA The latest release addresses this issue. Please take a look, and let us know if you need more help.

**Comment by ElAgroudyA** [comment] 2024-08-25 13:33
@tamayok It is fixed now, thanks.

**Closed** 2024-08-26 14:42 UTC
