### ISSUE TITLE
terminateInstance does not terminate the WebView instance from the app

### ISSUE THREAD

**Issue by ElAgroudyA** [Tealium/tealium-react-native#174] opened 2024-05-27 09:17 UTC
tealium-react-native version: 2.4.0
Platfrom: Android/iOS

My case is that I initialize Tealium with user login, then destroy Tealium instance by calling `Tealium.terminateInstance()` on user logout. When I login with different/or same user (without closing the app) a new instance gets created but the old instance did not get deleted from the app as seen in the dev inspector.

Expected:
`Tealium.terminateInstance()` should terminate the WebView and delete the instance.

Actual:
`Tealium.terminateInstance()` does not terminate the WebView instance, it stays there but inactive.

Screenshots:

- Android/Chrome:
<img width="452" alt="Android" src="https://github.com/Tealium/tealium-react-native/assets/105606226/c5f7bad2-4217-4fe1-8d7c-9c2723f3198c">

- iOS/Safari:
<img width="649" alt="iOS" src="https://github.com/Tealium/tealium-react-native/assets/105606226/d12586bf-2b79-40e9-a5b6-07cfbca111c2">

**Comment by Enricoza** [comment] 2024-05-27 16:22
Hi @ElAgroudyA, thank you for opening this.
We will look into this and let you know shortly.

**Comment by Enricoza** [comment] 2024-05-27 16:49
Hi again @ElAgroudyA, from my tests this doesn't appear to happen. 
Did you manage to reproduce the issue with the sample app linked in this repo? 
Alternatively can you share the initialization code you are using? And maybe the logs when the issue happens? 

Remember to redact any sensitive information if you are adding anything to this issue or just open a ticket to [https://support.tealiumiq.com/](https://support.tealiumiq.com/) with the full log and code.

**Comment by ElAgroudyA** [comment] 2024-05-28 08:52
Hello @Enricoza,

Thanks for getting back. Attached below are the initialization code and config used to initialize Tealium.

<img width="308" alt="init" src="https://github.com/Tealium/tealium-react-native/assets/105606226/0bde3485-2135-4f10-9871-045b01bda54e">

<img width="531" alt="config" src="https://github.com/Tealium/tealium-react-native/assets/105606226/3597ee21-51b7-487f-9571-8788d6cce692">

**Comment by Enricoza** [comment] 2024-05-28 08:59
Are you sure this is everything? 
Why are you adding `RemoteCommands` as a Dispatcher but then don't configure any Remote Command?

Also can you share the `trackView` and `trackEvent` implementations?

Finally can you share the logs in a ticket at [https://support.tealiumiq.com/](https://support.tealiumiq.com/)?

**Comment by ElAgroudyA** [comment] 2024-05-28 09:32
I have Remote Commands but I've removed them not to confuse you, will attach full code.
Also attaching `trackView` and `trackEvent`.
But I don't get what logs do you mean ?

<img width="499" alt="mainInit" src="https://github.com/Tealium/tealium-react-native/assets/105606226/8e5fb962-a3ea-43f6-9403-9bd65702d04a">
<img width="396" alt="Screenshot 2024-05-28 at 12 29 53 PM" src="https://github.com/Tealium/tealium-react-native/assets/105606226/1f7bb9f3-b864-4d14-a217-b28b54aabbf8">

**Comment by Enricoza** [comment] 2024-05-28 09:37
Thanks for the details. 
I mean the logs printed to the console by XCode or Android Studio, printed by the tealium sdk. They might be helpful to identify what is going on in your case.

**Comment by ElAgroudyA** [comment] 2024-05-28 09:43
There is nothing in the logs being printed by Tealium on logging out (terminating the instance).

**Comment by ElAgroudyA** [comment] 2024-06-03 12:22
Hello @Enricoza ,

Any updates regarding this issue ?

**Comment by craigrouse** [comment] 2024-06-03 13:53
@ElAgroudyA yes - we're working on a resolution at the moment. It looks like an issue in our Android SDK, though we are unable to reproduce the issue at all on iOS. This would indicate that there's something else going on on iOS that's causing the webview to hang around after you terminate the Tealium instance. It might be best to troubleshoot this on a call, so if you'd like to do that, please raise a ticket at support.tealiumiq.com, and we can arrange that. For the Android side of things, we hope to have a resolution very soon.

**Comment by ElAgroudyA** [comment] 2024-06-03 14:08
Hello @craigrouse ,

Thank you, let me tell you the steps to produce it on iOS

Put in mind my use case (I start tealium on user login and destorys the instance on user logout).
For the `first` app launch and `first` login it will work normally and destroy normally, if I logged in again with the same app instance/launch (did not close the app or minimize it) it will get bugged. It will start new instances on login but wont destory them on logout.

**Comment by craigrouse** [comment] 2024-06-03 14:13
@ElAgroudyA we tested with this exact scenario, and couldn't reproduce it on iOS. We'll take another look, but I think reviewing this with you on a call will be most efficient.

**Comment by ElAgroudyA** [comment] 2024-06-26 13:51
Hello,

I've been investigating in the iOS issue and found out that it happens when I turn on the 'AppDynamics' SDK
Any idea why would this happen?

https://www.npmjs.com/package/@appdynamics/react-native-agent

Thanks in advance @Enricoza @craigrouse

**Comment by craigrouse** [comment] 2024-06-26 14:05
@ElAgroudyA Thanks for the update. We're not familiar with the AppDynamics SDK, but after a quick glance at their docs, it appears they do performance instrumentation - is that correct? Chances are, they are probably doing a lot of swizzling under the hood, and there's a chance that this is creating a strong reference to our webview somewhere. Unfortunately, I think you'll need to take this up with AppDynamics' support team. If they need any input from us, we'd be glad to help - just create a support ticket at support.tealiumiq.com. Sorry we can't be of further assistance.

**Comment by ElAgroudyA** [comment] 2024-07-17 10:01
Hello @craigrouse @Enricoza ,

any updates regarding the android part of the issue ?

**Comment by craigrouse** [comment] 2024-07-17 10:21
@ElAgroudyA yes - the fix for Android will be released in the next couple of days.

**Closed** 2024-07-17 17:14 UTC

**Comment by ElAgroudyA** [comment] 2024-07-22 11:26
@tamayok , the issue still exists in the latest version on android.
Starting multiple instances doesn't close the old ones.
